name: Cron Job

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: https://github.com/openembedded/meta-openembedded
          mirror: true
