name: Deploy Changed Lambda Functions

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: us-east-2

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find and Deploy Modified Lambda Functions
        run: |
          # Enable associative array in Bash
          declare -A LAMBDA_MAP

          # Get previous and current commit hashes
          PREVIOUS_COMMIT=$(git log --format="%H" -n 2 | tail -n 1)
          CURRENT_COMMIT=$(git log --format="%H" -n 1)

          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only $PREVIOUS_COMMIT $CURRENT_COMMIT)
          
          # Loop through each changed file
          for changed_file in $CHANGED_FILES; do
              if [[ "$changed_file" == *"_lambda/"* ]]; then
                  echo changed_file: $changed_file
                  changed_dir=$(dirname "$changed_file")
                  echo changed_dir: $changed_dir
                  lambda_dir=$(basename "$changed_dir")
                  echo lambda_dir: $lambda_dir
                  lambda_name=$(echo "$lambda_dir" | sed -E 's/-lambda//')
                  echo lambda_name: $lambda_name
                  # Capitalize the first letter of lambda_name
                  capitalized="${lambda_name^}"
                  echo capitalized: $capitalized
                  function_name="iot-api${capitalized}Endpoints"
                  # Map the directory to the function name
                  LAMBDA_MAP[$function_name]="$changed_dir"
              fi
          done

          # Deploy each modified Lambda function
          for function_name in "${!LAMBDA_MAP[@]}"; do
              lambda_dir="${LAMBDA_MAP[$function_name]}"
              # Create a zip file for the Lambda function code
              (cd "$lambda_dir" && zip -r "${function_name}.zip" .)
              # Deploy the Lambda function
              echo "Deploying $function_name from $lambda_dir"
              aws lambda update-function-code --function-name "$function_name" --zip-file fileb://"${lambda_dir}/${function_name}.zip"
              echo "Deployed $function_name from $lambda_dir"
          done
