name: Cron Job

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: git clone --mirror https://github.com/openembedded/meta-openembedded
