name: Lint, Build and Publish (Prod)

on:
  push:
    tags:
      - "v*"

env:
  AWS_REGION: us-east-2

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Print all environment variables
        run: env
  
